steps:
  # ✅ Step 1: make.sh 스크립트 실행 (bash가 포함된 ubuntu 이미지 사용)
  - name: 'ubuntu'
    entrypoint: 'bash'
    args: ['make.sh', 'build_linux']

  # ✅ Step 2: Docker buildx 빌드
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'buildx', 'build',
        '--platform=linux/amd64',
        '-f', 'docker/Dockerfile',
        '-t', 'asia-northeast3-docker.pkg.dev/mp-artifact-registry-aa49/devops/qanda/fluent-bit:3.2.10-pubsub',
        '--push',
        '.'
      ]
    env:
      - DOCKER_CLI_EXPERIMENTAL=enabled
    entrypoint: 'docker'

timeout: 1200s
options:
  machineType: 'E2_HIGHCPU_8'
